apiVersion: v1
kind: Secret
metadata:
  name: k8s-secret
type: Opaque
stringData:
    mysql-admin: admin
    mysql-admin-password: admin_password
    mysql-db-user: user
    mysql-db-passwd: password
    db-name: vdescham_wp
    db-table-prefix: vdescham_wp_
    ssh-user: user
    ssh-password: password
    ftps-user: user
    ftps-password: password
    __INFLUXDB_NAME__: telegraf
    __INFLUXDB_USER__: user
    __INFLUXDB_PASSWORD__: password
    __GRAFANA_ADMIN_PASSWORD__: password
    __GRAFANA_ADMIN_NAME__: user
