apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: k8s-secret
              key: ftps_user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: k8s-secret
              key: ftps_password
        livenessProbe:
          exec:
            command:
            - sh
            - /srcs/liveness.sh
          initialDelaySeconds: 15
          periodSeconds: 3
        ports:
        - containerPort: 21
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
spec:
  type: LoadBalancer
  ports:
  - name: ftps
    port: 21
    targetPort: 21
  selector:
    app: ftps
