apiVersion: v1
kind: Secret
metadata:
  name: k8s-secret
type: Opaque
stringData:
  mysql_admin: admin
  mysql_admin-password: admin
  mysql_db-user: user
  mysql_db_password: password
  wp_db_name: ft_services
  wp_table_prefix: ft_
  ssh_user: user
  ssh_password: password
